from django.urls import path
from . import views 

urlpatterns = [ 
    path('', views.index, name='index'),
    path('signup/<str:pk>', views.signup, name='signup'),
    path('signin', views.signin, name='signin'),
    path('logout', views.logout, name='logout'),
    path('settings', views.settings, name='settings' ),
    path('profileEdit', views.profileEdit, name='profileEdit' ),
    path('profile/<str:pk>', views.profile, name='profile' ),
    path('connect', views.connect, name='connect'),
    path('react/<str:pk>', views.react, name='react'),
    path('post/<str:pk>', views.post, name='post'),
    path('delete_post/<str:pk>', views.delete_post, name='delete_post'),
    path('post_comment/<str:pk>', views.post_comment, name='post_comment'),
    path('addWorkExp', views.addWorkExp, name='addWorkExp'),
    path('searchWorker', views.searchWorker, name='searchWorker'),
    path('professionalExperiences', views.allWorks, name='allWorks'),
    path('editWork/<str:pk>', views.editWork, name='editWork'),
    path('deleteWork/<str:pk>', views.deleteWork, name='deleteWork'),
    path('followCompany/<str:pk>', views.followCompany, name='followCompany'),
    path('inbox', views.inbox, name='inbox'),
    path('message/<str:pk>', views.message, name='message'),
    path('verify', views.verifyAccount, name='verifyAccount'),
    path('adminVerify', views.adminVerify, name='adminVerify'),
    path('verifyRequest/<str:pk>', views.verifyRequest, name='verifyRequest'),
    path('welcome', views.become, name='become'),
    path('info', views.info, name='info'),
    path('getMessages/<str:pk>', views.getMessages, name='getMessages'), 
    path('meet', views.meet, name='meet'),
    path('room/<str:pk>', views.room),
    path('get_token/', views.getToken),

    path('create_member/', views.createMember),
    path('get_member/', views.getMember),
    path('delete_member/', views.deleteMember),
    path('getFriend/<str:pk>', views.getFriend, name='getFriend'), 
    path('inviteToMeet/<str:pk>', views.inviteToMeet, name='inviteToMeet'), 
    path('jobFilter/<str:pk>', views.jobFilter, name="jobFilter"),
    path('search', views.search, name="search"),
    path('allCompanies', views.allCompanies, name="allCompanies"),
    path('profileLocation', views.profileLocation, name="profileLocation"),
    path('checkReact/<str:pk>', views.checkReact, name="checkReact"),
    path('get_Notifications/<str:pk>', views.get_Notifications, name="get_Notifications"),


    path('predict', views.predict_animal, name="predict"),
]