# Generated by Django 3.2.13 on 2022-07-14 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.ImageField(blank=True, upload_to='verify_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='sector',
            field=models.TextField(blank=True),
        ),
    ]
