# Generated by Django 3.2.13 on 2022-07-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0002_auto_20220714_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
