# Generated by Django 3.2.13 on 2022-07-15 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0003_remove_profile_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preaccount',
            name='phone',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(blank=True, default=4, on_delete=django.db.models.deletion.CASCADE, to='profile_user.location'),
        ),
    ]
